# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Article.create(title:"Mitimae", body:"Les Mitimaes étaient des groupes de familles séparées de force de leurs communautés d'origine par l'Empire Inca, et déplacées depuis des villages loyaux vers des régions conquises et vice-versa, afin d'y remplir certaines fonctions économiques, sociales, culturelles, politiques et militaires. Le mot provient du quechua mitmac, ce qui signifie éparpiller. Ces groupes sont aussi connus comme mitmakuna ou mitmaqkuna. Aucune autre politique n'eut autant de répercussion tant sur la démographie que sur la composition ethnique andine que celle des mitimaes. On estime que plus d'un quart de la population de l'empire fut ainsi déplacée. La fonction politique et stratégique la plus fréquente de ces déplacements était la nécessité de l'Empire Inca de diviser les populations supposées constituer une menace pour les élites dirigeantes de l'empire. Ces vastes déplacement de population avaient pour effet de diminuer le poids d'une ethnie et d'affaiblir ainsi la possibilité de résister. La politique du mitmaqkuna fut surtout menée sur l'altiplano bolivien méridional. Là, les fonctions de ce type de colonisation furent à la fois productives et militaires de défense. Un grand nombre de Mitimaes furent obligés de défendre la frontière avec les Chiriguanos hostiles. Tout l'arc sud-est de l'altiplano fut parsemé de garnisons, et ce dispositif fut prolongé au sud dans l'actuel Nord-ouest argentin jusqu'au Pucará de Aconquija dans l'actuelle province de Tucuman.")
Article.create(title:"Arche du goût", body:"L'Arche du goût est un projet lancé, en 1996, par le mouvement Slow Food qui a pour mission de chercher, d'inventorier et de publier les produits alimentaires menacés d'extinction par la standardisation industrielle. Grâce au travail de recherche d'experts du monde entier réunis en 19 commissions nationales, aujourd'hui, elle accueille plus de 800 produits ou ressources biologiques intérieures provenant de plus de 50 pays. Utilisée à des fins d’information et de promotion, l'Arche sert de base de référence aux Presidi. La liste comprend non seulement des plats cuisinés et des produits alimentaires, mais aussi un grand nombre d'animaux de race ainsi que des légumes et des fruits aux saveurs presque oubliées.")
Article.create(title:"Pascal Dupuis", body:"Pascal Dupuis (né le 7 avril 1979 à Laval situé dans la province de Québec au Canada) est un joueur de hockey sur glace évoluant dans la Ligue nationale de hockey. Après avoir joué dans la Ligue de hockey junior majeur du Québec pendant quatre saisons, il rejoint en tant qu'agent libre et pour cinq saisons et demie le Wild du Minnesota de la Ligue nationale de hockey. Par la suite, il joue avec les Rangers de New York puis avec les Thrashers d'Atlanta avant de rejoindre en février 2008 les Penguins de Pittsburgh. La saison suivante, en 2008-2009, il remporte avec les Penguins la Coupe Stanley.")
Article.create(title:"Uzandı Deresi", body:"L’Uzandı Deresi1, Zondi Deresi2, Tabakhane Çayı3 (« rivière de la tannerie ») est une rivière turque coupée par le barrage de Gebere, traverse la ville de Niğde, puis est coupée par le barrage d'Akkaya avant de se perdre dans les hautes plaines au sud-ouest de Bor (1 100 m d'altitude).")
Article.create(title:"Coupe CECAFA des nations 2013", body:"La Coupe CECAFA des nations 2013 est la trente-septième édition de la Coupe CECAFA des nations qui a eu lieu au Kenya du 27 novembre au 12 décembre 2013. Les nations membres de la CECAFA (Confédération d'Afrique centrale et de l'Est) sont invitées à participer à la compétition. C'est le pays organisateur, le Kenya, qui remporte la compétition en s'imposant en finale face au Soudan.")
Article.create(title:"Tony Tomassi", body:"Tony Tomassi (15 janvier 1971 à Montréal - ) est un homme politique québécois de descendance italienne et ancien député de l'Assemblée nationale. De 2008 à 2010, il a été ministre de la Famille dans le gouvernement Charest. Il a été démis de ses fonctions et exclu du caucus du Parti libéral le 6 mai 2010 en raison de dépenses personnelles qu'il aurait fait avec une carte de crédit d'une compagnie privée alors qu'il était ministre. Il était au même moment au centre d'une controverse sur l'attribution de place en garderie par le gouvernement. Il a remis sa démission à titre de député le 3 mai 2012.")
Article.create(title:"Panhandle", body:"Un panhandle (anglicisme parfois traduit par le calque queue de poêle1 ou encore bande ou corridor) est, en géographie, une extension longue et étroite de la frontière d'une division administrative, dont la forme est similaire à la poignée d'une poêle. Le terme « panhandle » vient de l'anglais américain où il décrit la géographie particulière des frontières de certains États des États-Unis. Un panhandle est dans un sens similaire à une péninsule, laquelle est entourée par de l'eau de presque tous les côtés. Il peut correspondre à des nécessités géographiques (vallées en zone de montagne), politiques (nécessité de séparer ou relier deux États, comme le corridor du Wakhan), électorales (comme Bruxelles-ville), historiques (comme la Meurthe-et-Moselle créée après la guerre de 1870), etc. Il peut s'agir aussi d'accéder à une ressource dont un État ou une région ne disposerait pas sur sa partie principale (typiquement, la mer). Les panhandles sont assez fréquents dans le contexte colonial1.")
Article.create(title:"Les Versions longues", body:"Les Versions longues est une compilation d’Indochine accompagnant en 1996 la sortie du best of Unita. Il regroupe les versions remixées des singles du groupe sorties entre 1984 et 1991 sur maxi 45 tours vinyle et maxi CD single. Cet album, qui ne devait faire l'objet que d'une édition limitée, comme indiqué sur la pochette, a été réédité plusieurs fois par la maison de disques BMG. Il s'est vendu en France à plus de 20 000 exemplaires.")
Article.create(title:"Le Schtroumpfissime", body:"Le Schtroumpfissime est la neuvième histoire de la série Les Schtroumpfs de Peyo et Yvan Delporte. Elle est publiée pour la première fois de septembre 1964 à mai 1965 dans le journal Spirou, puis en 1965 dans le deuxième album de la série, également intitulé Le Schtroumpfissime, en compagnie de l'histoire Schtroumpfonie en ut. Elle met en scène le village des Schtroumpfs qui, pendant l'absence du Grand Schtroumpf, vote pour élire un chef. Une fois au pouvoir, le Schtroumpfissime met en place une dictature militaire, tandis que des Schtroumpfs rebelles luttent en secret contre lui. Cette histoire est une critique féroce de la démocratie représentative, accusée de mettre au pouvoir les individus les plus démagogues, lesquels s'empressent de trahir le peuple une fois élus. L'humour y est très présent, notamment le comique de répétition du cadeau explosif du Schtroumpf Farceur qui apparaît pour la première fois au cours de cette histoire et devient par la suite un élément récurrent de la série. Elle permet aussi d'introduire de nombreux personnages récurrents dans les histoires des Schtroumpfs qui suivront.")
Article.create(title:"Université de Paris", body:"L’université de Paris était l’une des plus importantes et des plus anciennes universités médiévales. Apparue dès le milieu du xiie siècle, elle est reconnue par le roi Philippe Auguste en 1200 et par le pape Innocent III en 1215. Elle acquiert rapidement un très grand prestige, notamment dans les domaines de la philosophie et de la théologie. Constituée comme l’association de tous les collèges parisiens situés sur la rive gauche, elle assurait la formation de tous les clercs, c’est-à-dire de tous les cadres et agents administratifs des institutions royales (conseil d’État, parlements, tribunaux, cours des comptes, impôts, etc.) et ecclésiastiques (enseignement, hôpitaux, libraires, recherche, évêques, abbés). L’université de Paris, après une longue période de déclin à l’époque moderne, est supprimée en 1793, et remplacée par des écoles supérieures spécialisées de droit, de médecine, d’ingénieurs, par les écoles normales, etc. Un peu plus d'un siècle plus tard, en 1896, l’université de Paris est réinstituée sur des bases différentes avec quatre facultés (droit, médecine, lettres, sciences), et environ encore un siècle plus tard, en 1971, elle est divisée en treize universités indépendantes. Hormis les établissements situés à la périphérie de Paris, celles de ces universités qui sont proprement parisiennes et issues de l'ancienne université, tendent à se reconstituer en trois ensembles fédérant autour d'eux quelques grandes écoles, Sorbonne Paris Cité (environ 106 000 étudiants), Sorbonne Universités (environ 66 000 étudiants ) et HESAM (Hautes Écoles, Sorbonne Arts set Métiers).")
